HW done
LoliPis/EqualsandHash pull request #1
Opened 2022-12-14 20:41 UTC by LoliPis

2022-12-15 07:25 UTC, OlgaLugacheva approved these changes

2022-12-15 07:25 UTC, OlgaLugacheva commented on src/Main.java
> +//        shopListFirst.addNewProduct(bananas);
не оставляем закомментированный код

2022-12-16 09:13 UTC, LoliPis commented on src/Main.java
> +//        shopListFirst.addNewProduct(bananas);
Я забыла убрать комментарий, закомментировала чтобы проверять работу программы дальше, так как там выбрасывается исключение

2022-12-16 18:08 UTC, OlgaLugacheva requested changes

2022-12-16 18:08 UTC, OlgaLugacheva commented on src/productsAndRecipes/Recipe.java
> +    private Set<Product> recipeProductsList = new LinkedHashSet<>();
вроде тут  должна быть мапа по заданию

2022-12-16 18:17 UTC, LoliPis commented on src/productsAndRecipes/Recipe.java
> +    private Set<Product> recipeProductsList = new LinkedHashSet<>();
Может я не тот пул кинула, просто смотрю файл класса recipe, у меня он заменен на мапу. ![image](https://user-images.githubusercontent.com/113059760/208163116-9b9fda59-3260-4057-9b02-803ac35d9326.png)

2022-12-16 18:20 UTC, merged